In [37]:
import pandas as pd

df = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests.csv")

In [38]:
df_law = df[df['subject']=="professional_law"]

In [39]:
df_law = df_law[:200]
df_law.reset_index(inplace=True,drop=True)

In [42]:
for idx,ele in df_law.iterrows():
    if idx < 100:
        df_law.loc[idx, "target_node"] = 0
    else:
        df_law.loc[idx, "target_node"] = 1

In [43]:
df_law

,text,target_node,subject
0,"One afternoon, a pilot was flying a small airp...",0,professional_law
1,"One afternoon, a pilot was flying a small airp...",0,professional_law
2,"One afternoon, a pilot was flying a small airp...",0,professional_law
3,"One afternoon, a pilot was flying a small airp...",0,professional_law
4,"One afternoon, a pilot was flying a small airp...",0,professional_law
...,...,...,...
195,"One afternoon, a pilot was flying a small airp...",1,professional_law
196,"One afternoon, a pilot was flying a small airp...",1,professional_law
197,"One afternoon, a pilot was flying a small airp...",1,professional_law
198,"One afternoon, a pilot was flying a small airp...",1,professional_law
199,"One afternoon, a pilot was flying a small airp...",1,professional_law

In [44]:
df_law.to_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_law_test_200.csv")

In [ ]:
df = df[:5]
df.to_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_5.csv")

In [64]:
import pandas as pd
import json
results = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/sglang_run_20260416_223418/results.csv",sep="|")
debug_data = []
with open("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/runs/sglang_run_20260416_223418/debug.jsonl","r", encoding='utf-8') as f:
    for line in f:
        # print(line)
        debug_data.append(json.loads(line))

In [65]:
for ele in debug_data[0:10]:
    print(ele)

{'request_id': 0, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1359, 'sglang_prompt_tokens': 1359, 'sglang_cache_hit_tokens': 0, 'sglang_cache_hit_ratio': 0.0, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 0, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1359}
{'request_id': 1, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1409, 'sglang_prompt_tokens': 1409, 'sglang_cache_hit_tokens': 1179, 'sglang_cache_hit_ratio': 0.8368, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1179, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1409}
{'request_id': 2, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1341, 'sglang_prompt_tokens': 1341, 'sglang_cache_hit_tokens': 1178, 'sglang_cache_hit_ratio': 0.8784, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1178, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1341}
{'request_id': 3, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1336, 'sglang_prompt_tokens': 1336, 'sglang_cache_hit_tokens': 1177, 'sglang_cache_hit_ratio': 0.881, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1177, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1336}
{'request_id': 4, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1408, 'sglang_prompt_tokens': 1408, 'sglang_cache_hit_tokens': 1177, 'sglang_cache_hit_ratio': 0.8359, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1177, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1408}
{'request_id': 5, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1336, 'sglang_prompt_tokens': 1336, 'sglang_cache_hit_tokens': 1178, 'sglang_cache_hit_ratio': 0.8817, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1178, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1336}
{'request_id': 6, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1607, 'sglang_prompt_tokens': 1607, 'sglang_cache_hit_tokens': 1178, 'sglang_cache_hit_ratio': 0.733, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1178, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1607}
{'request_id': 7, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1387, 'sglang_prompt_tokens': 1387, 'sglang_cache_hit_tokens': 1178, 'sglang_cache_hit_ratio': 0.8493, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1178, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1387}
{'request_id': 8, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1405, 'sglang_prompt_tokens': 1405, 'sglang_cache_hit_tokens': 1179, 'sglang_cache_hit_ratio': 0.8391, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1179, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1405}
{'request_id': 9, 'subject': 'professional_law', 'target_node': 0, 'ingress_node': 0, 'selected_node': 0, 'processed_by': 0, 'routed_from': None, 'routed_to': None, 'prefix_match_input_tokens': 1448, 'sglang_prompt_tokens': 1448, 'sglang_cache_hit_tokens': 1178, 'sglang_cache_hit_ratio': 0.8135, 'per_node_expected_cache_hits': [{'node_id': 0, 'expected_cache_hit_tokens': 1178, 'was_selected': True}, {'node_id': 1, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 2, 'expected_cache_hit_tokens': 0, 'was_selected': False}, {'node_id': 3, 'expected_cache_hit_tokens': 0, 'was_selected': False}], 'local_snapshot_match_after_process': 1448}

In [66]:
results

,request_id,subject,target_node,ingress_node,processed_by,routed_from,routed_to,prefix_match_input_tokens,expected_cache_hit_tokens,expected_cache_hit_ratio,sglang_prompt_tokens,sglang_cache_hit_tokens,sglang_cache_hit_ratio,local_snapshot_match_after_process,total_time_s,generated_text,error
0,0,professional_law,0,0,0,NaN,NaN,1359,0,0.0000,1359,0,0.0000,1359,0.0169,B,NaN
1,1,professional_law,0,0,0,NaN,NaN,1409,1179,0.8368,1409,1179,0.8368,1409,0.0091,A,NaN
2,2,professional_law,0,0,0,NaN,NaN,1341,1178,0.8784,1341,1178,0.8784,1341,0.0122,D,NaN
3,3,professional_law,0,0,0,NaN,NaN,1336,1177,0.8810,1336,1177,0.8810,1336,0.0113,D,NaN
4,4,professional_law,0,0,0,NaN,NaN,1408,1177,0.8359,1408,1177,0.8359,1408,0.0116,D,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,professional_law,1,1,0,1.0,0.0,1224,1181,0.9649,1224,1181,0.9649,1224,0.0144,B,NaN
196,196,professional_law,1,1,0,1.0,0.0,1335,1181,0.8846,1335,1181,0.8846,1335,0.0200,D,NaN
197,197,professional_law,1,1,0,1.0,0.0,1441,1180,0.8189,1441,1180,0.8189,1441,0.0204,B,NaN
198,198,professional_law,1,1,0,1.0,0.0,1460,1178,0.8068,1460,1178,0.8068,1460,0.0209,C,NaN
199,199,professional_law,1,1,0,1.0,0.0,1248,1177,0.9431,1248,1177,0.9431,1248,0.0198,C,NaN

In [6]:
import pandas as pd
df_law = pd.read_csv("/home/ssn899/Desktop/P2P_LLM/Distributed-Inference-for-Edge-LLMs/datasets/requests_law_200.csv")

In [9]:
df_law['text'][0]

'One afternoon, a pilot was flying a small airplane when it suddenly ran out of gas. As he was coming in for an emergency landing, the plane crossed into a neighboring state at a very low altitude. At this time, a 9-year-old boy was walking to school when he was struck and injured by an object, which may have fallen from the plane. In federal court, a negligence suit was brought against the pilot by the father of the boy for his son. Accompanied by his father, the boy had visited an attorney for preliminary discussions regarding the case. However, the father did not retain the attorney to represent his son in the lawsuit. Instead, the father hired another lawyer to handle the case. At trial, the pilot\'s attorney calls the consulting attorney to testify what the boy had said to him regarding his physical condition during the consultation that the attorney had had with the boy and his father. The attorney\'s testimony is\nA. admissible, because the attorney-client privilege was waived by the filing of the lawsuit.\nB. admissible, because there is no privilege of confidentiality when a person other than the client is present at the attorney-client consultation.\nC. inadmissible, because the attorney-client privilege prevents such a breach of confidential communications.\nD. inadmissible, because it was a statement of physical condition not made for the purpose of obtaining medical treatment.\nAnswer: C\n\nA state statute provides: "Whenever a person knows or should know that he (or she) is being arrested by a police officer, it is the duty of such person to refrain from using force or any weapon in resisting arrest. " Violation of the statute is made punishable by fine and/or imprisonment. One morning, there was a bank robbery in the state. That afternoon, a police officer arrested a suspect who he believed was involved in the crime. However, the police officer and the suspect have given different accounts concerning what happened next. According to the police officer, after the suspect was apprehended, he resisted arrest and hit the police officer in the mouth with his fist. The police officer, who was momentarily stunned, pulled out his nightstick and struck the suspect over the head with it. On the other hand, the suspect claimed that after he was arrested, he cursed at the policeman, whereupon the police officer began hitting the suspect with his nightstick. To avoid being hit again, the suspect hit the police officer with his fist, knocking him down. The suspect was charged with assault. The suspect should be found\nA. not guilty, if the arrest was unlawful without probable cause and the jury believes the suspect\'s account.\nB. not guilty, if the arrest was lawful, provided that the jury believes the suspect\'s account.\nC. guilty, if the arrest was lawful, regardless which account the jury believes.\nD. guilty, if the arrest was unlawful, regardless which account the jury believes.\nAnswer: B\n\nA taxpayer was notified by the government that her individual income tax was underpaid by $1,012. 69. The taxpayer retained an attorney to represent her in contesting the assessment. During the preparation of his client\'s case, the attorney suggested that it might be a good idea if the taxpayer hired an accountant to organize her records and prepare a financial statement for the year in question. Following the attorney\'s advice, the taxpayer consulted an accountant, an old family friend, who prepared a financial statement, which the attorney referred to at trial. During the trial, the attorney representing the government called the accountant to testif\' about statements that the taxpayer made to him. The accountant\'s proposed testimony is\nA. inadmissible, because it would violate the attorney-client privilege.\nB. inadmissible, because it would violate the taxpayer\'s privilege against self-incrimination.\nC. inadmissible as violative of the work-product rule.\nD. admissible as an admission.\nAnswer: D\n\nA resident announced his candidacy for state representative. A law in the state requires new political entrants (regardless of party affiliation) to obtain three times the number of signatures as other candidates who have run for office previously. The resident, however, failed to obtain the necessary number of authenticating signatures to have his name placed on the ballot. The resident filed a complaint in federal district court alleging the unconstitutionality of the authenticating requirement. Which of the following, if established, is the state\'s strongest argument for sustaining the validity of the authenticating requirement?\nA. The resident\'s petition contained a large number of false signatures.\nB. A similar authenticating statute was held to be constitutional in another state the previous year.\nC. The authenticating requirement was necessary to further a compelling state interest.\nD. Two other candidates had successfully petitioned to have their names included on the ballot.\nAnswer: C\n\nA defendant was angry at his friend for marrying the defendant\'s former girlfriend. As the friend was painting his house one afternoon, the defendant fired a shot from his gun at him. Although the shot missed the friend, the bullet struck and killed the friend\'s daughter. The defendant is subsequently charged with the first-degree murder of the daughter. The relevant statutes in effect in this jurisdiction are as follows:Section 169: Murder in the first degree is the unlawful and intentional killing of a human being with malice aforethought. Section 170: Malice is expressed when there is manifested a deliberate intention to take away the life of another. Which of the following, if established, would provide the defendant with his best defense?\nA. He intended to kill the friend and not the daughter.\nB. He intended only to wound the friend.\nC. He was unaware of the elements of malice.\nD. The killing was the result of negligence in missing the friend.\nAnswer: B\n\nA man and a woman had a romantic relationship for one year, but the man ended it. The woman was unable to accept the breakup and continued trying to contact the man. The woman would call the man\'s home and cellphone many times each day, and also tried to visit the man\'s home and workplace frequently. The man tried to discourage the woman\'s behavior, but the woman persisted. If the man asserts a claim against the woman based on invasion of privacy, the most likely outcome is that the man will\nA. prevail, because the telephone calls intruded upon his seclusion and solitude.\nB. prevail, but only if the man is able to prove malice on the defendant\'s part.\nC. not prevail, because the telephone calls did not cause the man to suffer any economic loss or hardship.\nD. not prevail, unless the woman\'s conduct was a crime in some respect.\nAnswer:'

In [10]:
df_law['text'][1]

'One afternoon, a pilot was flying a small airplane when it suddenly ran out of gas. As he was coming in for an emergency landing, the plane crossed into a neighboring state at a very low altitude. At this time, a 9-year-old boy was walking to school when he was struck and injured by an object, which may have fallen from the plane. In federal court, a negligence suit was brought against the pilot by the father of the boy for his son. Accompanied by his father, the boy had visited an attorney for preliminary discussions regarding the case. However, the father did not retain the attorney to represent his son in the lawsuit. Instead, the father hired another lawyer to handle the case. At trial, the pilot\'s attorney calls the consulting attorney to testify what the boy had said to him regarding his physical condition during the consultation that the attorney had had with the boy and his father. The attorney\'s testimony is\nA. admissible, because the attorney-client privilege was waived by the filing of the lawsuit.\nB. admissible, because there is no privilege of confidentiality when a person other than the client is present at the attorney-client consultation.\nC. inadmissible, because the attorney-client privilege prevents such a breach of confidential communications.\nD. inadmissible, because it was a statement of physical condition not made for the purpose of obtaining medical treatment.\nAnswer: C\n\nA state statute provides: "Whenever a person knows or should know that he (or she) is being arrested by a police officer, it is the duty of such person to refrain from using force or any weapon in resisting arrest. " Violation of the statute is made punishable by fine and/or imprisonment. One morning, there was a bank robbery in the state. That afternoon, a police officer arrested a suspect who he believed was involved in the crime. However, the police officer and the suspect have given different accounts concerning what happened next. According to the police officer, after the suspect was apprehended, he resisted arrest and hit the police officer in the mouth with his fist. The police officer, who was momentarily stunned, pulled out his nightstick and struck the suspect over the head with it. On the other hand, the suspect claimed that after he was arrested, he cursed at the policeman, whereupon the police officer began hitting the suspect with his nightstick. To avoid being hit again, the suspect hit the police officer with his fist, knocking him down. The suspect was charged with assault. The suspect should be found\nA. not guilty, if the arrest was unlawful without probable cause and the jury believes the suspect\'s account.\nB. not guilty, if the arrest was lawful, provided that the jury believes the suspect\'s account.\nC. guilty, if the arrest was lawful, regardless which account the jury believes.\nD. guilty, if the arrest was unlawful, regardless which account the jury believes.\nAnswer: B\n\nA taxpayer was notified by the government that her individual income tax was underpaid by $1,012. 69. The taxpayer retained an attorney to represent her in contesting the assessment. During the preparation of his client\'s case, the attorney suggested that it might be a good idea if the taxpayer hired an accountant to organize her records and prepare a financial statement for the year in question. Following the attorney\'s advice, the taxpayer consulted an accountant, an old family friend, who prepared a financial statement, which the attorney referred to at trial. During the trial, the attorney representing the government called the accountant to testif\' about statements that the taxpayer made to him. The accountant\'s proposed testimony is\nA. inadmissible, because it would violate the attorney-client privilege.\nB. inadmissible, because it would violate the taxpayer\'s privilege against self-incrimination.\nC. inadmissible as violative of the work-product rule.\nD. admissible as an admission.\nAnswer: D\n\nA resident announced his candidacy for state representative. A law in the state requires new political entrants (regardless of party affiliation) to obtain three times the number of signatures as other candidates who have run for office previously. The resident, however, failed to obtain the necessary number of authenticating signatures to have his name placed on the ballot. The resident filed a complaint in federal district court alleging the unconstitutionality of the authenticating requirement. Which of the following, if established, is the state\'s strongest argument for sustaining the validity of the authenticating requirement?\nA. The resident\'s petition contained a large number of false signatures.\nB. A similar authenticating statute was held to be constitutional in another state the previous year.\nC. The authenticating requirement was necessary to further a compelling state interest.\nD. Two other candidates had successfully petitioned to have their names included on the ballot.\nAnswer: C\n\nA defendant was angry at his friend for marrying the defendant\'s former girlfriend. As the friend was painting his house one afternoon, the defendant fired a shot from his gun at him. Although the shot missed the friend, the bullet struck and killed the friend\'s daughter. The defendant is subsequently charged with the first-degree murder of the daughter. The relevant statutes in effect in this jurisdiction are as follows:Section 169: Murder in the first degree is the unlawful and intentional killing of a human being with malice aforethought. Section 170: Malice is expressed when there is manifested a deliberate intention to take away the life of another. Which of the following, if established, would provide the defendant with his best defense?\nA. He intended to kill the friend and not the daughter.\nB. He intended only to wound the friend.\nC. He was unaware of the elements of malice.\nD. The killing was the result of negligence in missing the friend.\nAnswer: B\n\nA man owned a piece of land with a run-down log cabin on it. He lost interest in it, letting tax bills pile up and failing to maintain it. In 1990, a homeless couple occupied the crumbling cabin. They restored it, fenced the perimeter, and maintained the grounds. They started paying the taxes, despite knowing there was an absentee owner. In 2000, the owner appeared and demanded that they pay rent. They agreed but stopped the payments two years later after consulting an attorney. The required statutory period in the state is 20 years. In 2011 the owner filed an ejectment action, asserting his ownership rights. Leaving aside any other theories or equities, can the couple prevail on a theory of adverse possession?\nA. Yes, because they were on the land for over 20 years.\nB. No, because they missed some of the tax payments during that 20-year period.\nC. No, because the hostile possession was interrupted for two years when they paid rent.\nD. Yes, because they owned the property due to paying the taxes on it.\nAnswer:'

In [ ]:
for i in range(len(results)):